name: Create release

on:
  push:
    tags:
      - "dummy-v*"
    branches:
      - "mojo-plugin"

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    
      - run: |
         sudo apt update && sudo apt install build-essential libfile-sharedir-perl
         perl Makefile.PL
         make manifest dist
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: Changes
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Contenticious-0.393.tar.gz
          asset_name: Contenticious-0.393.tar.gz
          asset_content_type: application/gzip
